import streamlit as st
from groq import Groq
from google import genai
from google.genai import types
from PIL import Image
from datetime import datetime
import PyPDF2
from docx import Document
import io

# --- 1. PAGE SETUP ---
st.set_page_config(page_title="Adrito's Nano AI", page_icon="🍌", layout="wide")

# --- 2. SESSION STATE ---
if "all_sessions" not in st.session_state:
    st.session_state.all_sessions = {"New Chat Session": []}
if "current_chat" not in st.session_state:
    st.session_state.current_chat = "New Chat Session"

# --- 3. FILE PARSERS ---
def extract_text(file):
    try:
        fname = file.name.lower()
        if fname.endswith(('.txt', '.py', '.md')):
            return file.read().decode("utf-8")
        elif fname.endswith('.pdf'):
            reader = PyPDF2.PdfReader(file)
            return "\n".join([p.extract_text() for p in reader.pages if p.extract_text()])
        elif fname.endswith('.docx'):
            doc = Document(io.BytesIO(file.read()))
            return "\n".join([p.text for p in doc.paragraphs])
    except Exception as e:
        st.sidebar.error(f"File Error: {e}")
    return ""

# --- 4. SIDEBAR (Unified Model Map) ---
MODEL_MAP = {
    "🔥 Pro (GPT-OSS 120B)": "openai/gpt-oss-120b",
    "⚖️ Balanced (GPT-OSS 70B)": "openai/gpt-oss-70b",
    "⚡ Lightning (GPT-OSS 20B)": "openai/gpt-oss-20b",
    "🎨 Nano Banana (Image Gen ONLY)": "NANO_BANANA_IMAGE_MODE"
}

with st.sidebar:
    st.title("⚙️ AI Control")
    
    friendly_options = list(MODEL_MAP.keys())
    selected_label = st.selectbox(
        "🧠 Choose Brain Power",
        options=friendly_options,
        index=0,
        key="model_selector_unified"
    )
    model_choice = MODEL_MAP[selected_label]
    
    is_image_mode = (model_choice == "NANO_BANANA_IMAGE_MODE")
    
    if not is_image_mode:
        web_search = st.toggle("Enable Live Web Search", value=True)
        uploaded_file = st.file_uploader("📎 Upload (.txt, .pdf, .docx)", type=['txt', 'py', 'md', 'pdf', 'docx'])
    else:
        st.info("🎨 Nano Banana is active. Type an image prompt below.")
    
    st.divider()
    st.header("📂 Chat Management")
    
    if st.button("➕ Start New Chat", use_container_width=True):
        new_id = f"Session {datetime.now().strftime('%H:%M:%S')}"
        st.session_state.all_sessions[new_id] = []
        st.session_state.current_chat = new_id
        st.rerun()

    if len(st.session_state.all_sessions) > 1:
        if st.button("🗑️ Delete All History", use_container_width=True, type="secondary"):
            st.session_state.all_sessions = {"New Chat Session": []}
            st.session_state.current_chat = "New Chat Session"
            st.rerun()

    st.divider()
    st.subheader("Recent Chats")
    for chat_title in list(st.session_state.all_sessions.keys()):
        cols = st.columns([0.8, 0.2])
        if cols[0].button(chat_title, key=f"btn_{chat_title}", use_container_width=True, 
                          type="primary" if chat_title == st.session_state.current_chat else "secondary"):
            st.session_state.current_chat = chat_title
            st.rerun()
        if len(st.session_state.all_sessions) > 1:
            if cols[1].button("❌", key=f"del_{chat_title}"):
                del st.session_state.all_sessions[chat_title]
                st.session_state.current_chat = list(st.session_state.all_sessions.keys())[0]
                st.rerun()

# --- 5. MAIN INTERFACE ---
st.title(f"🚀 {st.session_state.current_chat}")

try:
    groq_client = Groq(api_key=st.secrets["GROQ_API_KEY"])
    google_client = genai.Client(api_key=st.secrets["GEMINI_API_KEY"])
except:
    st.error("Missing API Keys in Secrets!")
    st.stop()

messages = st.session_state.all_sessions[st.session_state.current_chat]
for msg in messages:
    with st.chat_message(msg["role"]):
        if "image" in msg:
            st.image(msg["image"], caption="Generated by Nano Banana 2")
        else:
            st.markdown(msg["content"])

# --- 6. UNIFIED CHAT LOGIC ---
if prompt := st.chat_input("Ask or Generate..."):
    messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        placeholder = st.empty()
        full_res = ""

        if is_image_mode:
            with st.status("🍌 Nano Banana is peeling your image..."):
                try:
                    response = google_client.models.generate_content(
                        model="gemini-3.1-flash-image-preview", 
                        contents=[prompt],
                        config=types.GenerateContentConfig(
                            response_modalities=["Image"],
                            image_config=types.ImageConfig(aspect_ratio="16:9")
                        )
                    )
                    for part in response.candidates[0].content.parts:
                        if part.inline_data:
                            img_data = part.inline_data.data
                            image = Image.open(io.BytesIO(img_data))
                            st.image(image)
                            messages.append({"role": "assistant", "image": image})
                except Exception as e:
                    st.error(f"Image Error: {e}")

        else:
            context = ""
            if uploaded_file:
                file_text = extract_text(uploaded_file)
                context = f"\n\n[FILE ATTACHED: {uploaded_file.name}]\n{file_text}"
            
            full_prompt = prompt + context
            sys_msg = f"Today is {datetime.now().strftime('%B %d, %Y')}. Web Search: {web_search}. You are a 2026 AI."
            
            try:
                stream = groq_client.chat.completions.create(
                    model=model_choice,
                    messages=[{"role": "system", "content": sys_msg}] + messages[:-1] + [{"role": "user", "content": full_prompt}],
                    stream=True
                )
                for chunk in stream:
                    if chunk.choices[0].delta.content:
                        full_res += chunk.choices[0].delta.content
                        placeholder.markdown(full_res + "▌")
                placeholder.markdown(full_res)
                messages.append({"role": "assistant", "content": full_res})
            except Exception as e:
                st.error(f"API Error: {e}")

    # --- 7. SMART NAMING ---
    is_default = any(x in st.session_state.current_chat for x in ["Session", "New Chat"])
    if len(messages) >= 2 and is_default:
        try:
            name_gen = groq_client.chat.completions.create(
                model="openai/gpt-oss-20b",
                messages=[
                    {"role": "system", "content": "Return exactly 2 words summarizing this topic. No quotes."},
                    {"role": "user", "content": prompt}
                ]
            )
            smart_title = name_gen.choices[0].message.content.strip().replace('"', '')
            st.session_state.all_sessions[smart_title] = st.session_state.all_sessions.pop(st.session_state.current_chat)
            st.session_state.current_chat = smart_title
            st.rerun()
        except: pass
